### ISSUE TITLE
Unable to negotiate at correct speed

### ISSUE THREAD

**Issue by scramble45** [Berzerker/google-fiber-2gbps-bypass#1]
Recently upgraded to 2Gbps Google Fiber, I followed your instructions outlined in this repo using exact Broadcom card. I show that the card in the `Ediag` is set to `2_5GB` and that the various values match what you have. I see following but I am not showing the correct speed under the supported media at the interface level itself. I am using the Google branded SFP+ module model: `GFLT210`. I've try removing and re-adding the interface in opnsense without any luck, but it does seem like the patched module is loading.

`NIC Link is Up, 2500 Mbps full duplex, Flow control: ON - receive & transmit`

![Capture1](https://user-images.githubusercontent.com/1687839/115131958-cfdffe80-9fc1-11eb-81f3-6760987fdf01.PNG)

![Capture2](https://user-images.githubusercontent.com/1687839/115131960-d1a9c200-9fc1-11eb-9008-b8c5ed373b00.PNG)

![Capture3](https://user-images.githubusercontent.com/1687839/115131961-d3738580-9fc1-11eb-9452-322fd9bcb0e6.PNG)

![Capture4](https://user-images.githubusercontent.com/1687839/115131962-d53d4900-9fc1-11eb-8949-d571f4e465ea.PNG)

![image](https://user-images.githubusercontent.com/1687839/115132161-5d701e00-9fc3-11eb-85fa-659497b27fde.jpeg)

**Comment by Berzerker** [comment]
I actually show the same as you. My link speed is 2500Mbps, but opnsense shows it as a 10Gbase-SR module, which is technically correct.

It doesn't affect my speed though, I still see 2000/1000 on speed tests.

**Comment by scramble45** [comment]
@Berzerker thanks for quick reply on this. How are your measuring your speed? I'm running the speedtest cli on the opnsense box and seeing gigabit speeds. Perhaps the server I'm hitting?

**Comment by Berzerker** [comment]
Might be, check http://speedtest.googlefiber.net/

**Comment by scramble45** [comment]
Yeah I was wanting to try that, I don't currently have any means of testing outside of the router itself atm. I will close this for now and try again when I have everything. Thank you.

**Comment by scramble45** [comment]
Just a quick update. I am able to obtain speeds in excess of 1gbps, around 1.5gbps on my setup, not sure the bottleneck at this time, but seems to work. Thanks again.
