### ISSUE TITLE
Revert spf card settings

### ISSUE THREAD

**Issue by torresdrew** [Berzerker/google-fiber-2gbps-bypass#3]
Do you happen to have documentation to revert the change in the dual spf card to make the port 10gb instead of 2.5gb?

**Comment by Berzerker** [comment]
Hello. I unfortunately do not, you might try posting in that DSLReports thread, or perhaps trying to find some documentation on the eDiag commands for the card.

**Comment by torresdrew** [comment]
Was looking at the doc now. Appreciate the response! I may post on the DSLReports thread too!

**Comment by Berzerker** [comment]
Please let us all know here if you do figure out a way!
